apiVersion: v1
kind: Service
metadata:
  name: billing
  labels:
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.billing.port }}
      targetPort: {{ .Values.service.billing.targetport }}
      protocol: TCP
      name: http
  selector:
    app: billing
