apiVersion: v1
kind: Service
metadata:
  name: notify
  labels:
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.notify.port }}
      targetPort: {{ .Values.service.notify.targetport }}
      protocol: TCP
      name: http
  selector:
    app: notify
