apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.auth.port }}
      targetPort: {{ .Values.service.auth.targetport }}
      protocol: TCP
      name: http
  selector:
    app: auth
