apiVersion: v1
kind: Service
metadata:
  name: windows
  labels:
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.windows.port }}
      targetPort: {{ .Values.service.windows.targetport }}
      protocol: TCP
      name: http
  selector:
    app: windows
