apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.store.port }}
      targetPort: {{ .Values.service.store.targetport }}
      protocol: TCP
      name: http
  selector:
    app: store
